# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='star_power',
            field=models.IntegerField(default=0),
        ),
    ]
