# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0002_profile_star_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='star_power',
            field=models.IntegerField(default=5),
        ),
    ]
