# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorme', '0003_auto_20170929_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default='', max_length=120),
        ),
    ]
